spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 12345
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
  application:
    name: yichou-redis
server:
  port: 3000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/